name: Publicar Extensão VS Code

on:
  push:
    tags:
      - 'v*' # Dispara automaticamente quando uma nova tag de versão for criada, ex: v0.1.1

permissions:
  contents: read

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: vscode-harpia/package-lock.json

      - name: Instalar Dependências
        run: npm ci
        working-directory: vscode-harpia

      - name: Publicar no VS Code Marketplace
        run: npx @vscode/vsce publish --pat ${{ secrets.VSCE_PAT }}
        working-directory: vscode-harpia
